version: '3.1'

services:
  pg-dev:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: mj
    ports:
      - 5432:5432
    volumes:
    - "$PWD/scripts/init-db-for-test.sh:/docker-entrypoint-initdb.d/init-user-db.sh"